---
kind: pipeline
type: kubernetes
name: build

steps:
- name: build
  image: maven:3-jdk-11
  commands:
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

trigger:
  event:
  - push
  - pull_request

---
kind: pipeline
type: kubernetes
name: deploy

steps:
- name: authenticate
  image: robertstettner/drone-mvn-auth
  settings:
    servers:
      from_secret: maven_servers

- name: deploy
  image: maven:3-jdk-11
  commands:
  - mvn tomcat7:redeploy -B --global-settings settings.xml

trigger:
  event:
  - promote
  target:
  - production
