---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: maven:3-jdk-11
  commands:
  - mvn package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

- name: authenticate
  image: robertstettner/drone-mvn-auth

- name: deploy
  image: maven:3-jdk-11
  commands:
  - mvn tomcat7:redeploy -B
